---
name: Run Ansible Playbooks

on:
    push:
        branches:
            - main
        paths:
            - ".github/workflows/runplays.yaml"
            - "ansible/**"
            - "!**/facts/**"
    workflow_dispatch:

jobs:
    Ping-Playbook:
        runs-on: minidell
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Create virtualenv
              run: |
                  python3 -m venv ./.venv
                  . .venv/bin/activate
                  echo PATH=$PATH >> $GITHUB_ENV

            - name: Install Ansible
              run: |
                  pip install Ansible
                  pip install -r requirements.txt

            - name: Install Ansible Collections
              run: |
                  ansible-galaxy install -r ansible/requirements.yaml

            - name: Execute Ping Playbook
              run: ansible-playbook ansible/playbooks/configure-junipers/configure-junipers.yaml -i ansible/inventory
