---
name: Echo Test

on:
    push:
        branches:
            - main
        paths:
            - ".github/workflows/test.yaml"
    workflow_dispatch:

jobs:
    Echo:
        runs-on: minidell
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Echo
              run: echo "First Run!"

        #   - name: Execute Ping Playbook
        #     run: ansible-playbook ansible/ping.yml -i ansible/inventory.ini
